# Generated by Django 4.2.6 on 2023-10-24 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cables", "0001_initial"),
        ("equipments", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="equipmentcategory",
            options={"verbose_name_plural": "Equipment categories"},
        ),
        migrations.AlterField(
            model_name="equipment",
            name="cables",
            field=models.ManyToManyField(blank=True, to="cables.cable"),
        ),
        migrations.AlterField(
            model_name="equipment",
            name="status",
            field=models.CharField(
                choices=[("open", "개방"), ("close", "투입")],
                default="open",
                max_length=10,
                verbose_name="상태",
            ),
        ),
    ]
