# Generated by Django 4.2.6 on 2023-10-11 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("status", models.BooleanField(default=False, verbose_name="상태")),
                (
                    "voltage_type",
                    models.CharField(
                        blank=True,
                        choices=[("ac", "AC"), ("dc", "DC")],
                        max_length=2,
                        null=True,
                        verbose_name="전압 종류",
                    ),
                ),
                (
                    "voltage",
                    models.SmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="전압[V]",
                    ),
                ),
                (
                    "specification",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="규격"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
